/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.frames;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.classes.DBmysqlconnection;

/**
 *
 * @author me
 */
public class Deals extends javax.swing.JFrame {

    /**
     * Creates new form Items
     */
    DBmysqlconnection s;
    String name;
    int i,itemdetailslist;
    public Deals(DBmysqlconnection s) {
        this.s =s;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        txtItemsID.setEditable(false);
        txtItemsID.setVisible(false);
        jLabel2.setVisible(false);
        s.ShowDealsIntable(tblItems);
        s.ShowItemsInComboBox(combolistcatagory);
        combolistcatagory.setVisible(false);
        txtDone.setVisible(false);
        jLabel6.setVisible(false);
        
        
//        this.s.loadCatagorycomboBox(combolistcatagory);
//        txttotalItems.setText();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtItemsID = new javax.swing.JTextField();
        txtItemItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDone = new javax.swing.JButton();
        btnItemReset = new javax.swing.JButton();
        btnItemEdit = new javax.swing.JButton();
        btnItemDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtItemRate = new javax.swing.JTextField();
        combolistcatagory = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItemsOrignal = new javax.swing.JTable();
        btnItemAdd1 = new javax.swing.JButton();
        btnItemEdit1 = new javax.swing.JButton();
        btnItemEdit2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Manage Deals");
        jLabel1.setOpaque(true);

        tblItems.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DealID", "DealName", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItems.setRowHeight(20);
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItems);
        if (tblItems.getColumnModel().getColumnCount() > 0) {
            tblItems.getColumnModel().getColumn(0).setMinWidth(1);
            tblItems.getColumnModel().getColumn(0).setPreferredWidth(1);
            tblItems.getColumnModel().getColumn(0).setMaxWidth(1);
        }

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("ID");

        txtItemsID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtItemsID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        txtItemItem.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtItemItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("DealName");

        txtDone.setBackground(new java.awt.Color(204, 255, 204));
        txtDone.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDone.setText("Done");
        txtDone.setContentAreaFilled(false);
        txtDone.setOpaque(true);
        txtDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoneActionPerformed(evt);
            }
        });

        btnItemReset.setBackground(new java.awt.Color(204, 255, 204));
        btnItemReset.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemReset.setText("Reset");
        btnItemReset.setContentAreaFilled(false);
        btnItemReset.setOpaque(true);
        btnItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemResetActionPerformed(evt);
            }
        });

        btnItemEdit.setBackground(new java.awt.Color(204, 255, 204));
        btnItemEdit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemEdit.setText("Edit");
        btnItemEdit.setContentAreaFilled(false);
        btnItemEdit.setOpaque(true);
        btnItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemEditActionPerformed(evt);
            }
        });

        btnItemDelete.setBackground(new java.awt.Color(204, 255, 204));
        btnItemDelete.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemDelete.setText("Delete");
        btnItemDelete.setContentAreaFilled(false);
        btnItemDelete.setOpaque(true);
        btnItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDeleteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setText("Price");

        txtItemRate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtItemRate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        combolistcatagory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combolistcatagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolistcatagoryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setText("Items");

        tblItemsOrignal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        tblItemsOrignal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "subdealid", "Item Name", "QTY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItemsOrignal.setRowHeight(20);
        tblItemsOrignal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsOrignalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItemsOrignal);

        btnItemAdd1.setBackground(new java.awt.Color(204, 255, 204));
        btnItemAdd1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemAdd1.setText("Create");
        btnItemAdd1.setContentAreaFilled(false);
        btnItemAdd1.setOpaque(true);
        btnItemAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemAdd1ActionPerformed(evt);
            }
        });

        btnItemEdit1.setBackground(new java.awt.Color(204, 255, 204));
        btnItemEdit1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemEdit1.setText("Delete item");
        btnItemEdit1.setContentAreaFilled(false);
        btnItemEdit1.setOpaque(true);
        btnItemEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemEdit1ActionPerformed(evt);
            }
        });

        btnItemEdit2.setBackground(new java.awt.Color(204, 255, 204));
        btnItemEdit2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemEdit2.setText("Update Table");
        btnItemEdit2.setContentAreaFilled(false);
        btnItemEdit2.setOpaque(true);
        btnItemEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemEdit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtItemRate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtItemItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(txtItemsID, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(combolistcatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnItemAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnItemEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnItemEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnItemEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnItemAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnItemEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnItemEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtItemsID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtItemItem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtItemRate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(combolistcatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtDone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnItemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemResetActionPerformed
            btnItemEdit2.setVisible(false);
            txtDone.setVisible(false);
            jLabel6.setVisible(false);
            combolistcatagory.setVisible(false);
            txtItemItem.setText("");
            txtItemRate.setText("");
            txtItemsID.setText("");
             DefaultTableModel model = (DefaultTableModel) tblItemsOrignal.getModel();
             model.setRowCount(0);                
    }//GEN-LAST:event_btnItemResetActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu m = new Menu(s);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosed

    private void combolistcatagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolistcatagoryActionPerformed
    DefaultTableModel model = (DefaultTableModel) tblItemsOrignal.getModel();
    String name = (String) combolistcatagory.getSelectedItem();
    if(name.equals(" ")){
        
    }
        
    if(!(name.equals(" "))){
    if(!(checkforname(name)) ){
    Object[] row = {"-1",name,"1"};
    model.addRow(row);
    }}
            
        
    }//GEN-LAST:event_combolistcatagoryActionPerformed

    private boolean checkforname(String Name){
            DefaultTableModel model = (DefaultTableModel) tblItemsOrignal.getModel();
            for (int j = 0; j < model.getRowCount(); j++) {
            if(tblItemsOrignal.getValueAt(j, 1).equals(Name)){
                return true;
            }
        }
            return false;
    }
    
    private void txtDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoneActionPerformed
           
        if(txtItemRate.getText().equals("")||txtItemItem.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fields Cannot be empty");
        }else if(s.checkfornameinDeals(txtItemItem.getText())!= -1){
        try{           
            boolean b = s.InsertDataInDeals(Double.parseDouble(txtItemRate.getText()),txtItemItem.getText());
            if(b){
               txtItemItem.setText("");
               txtItemRate.setText("");
               txtItemsID.setText("");
               txtDone.setVisible(false);
               jLabel6.setVisible(false);
               combolistcatagory.setVisible(false);
               int a =s.getLastDealsID(); 
                for (int j = 0; j < tblItemsOrignal.getRowCount(); j++) {
                
                        s.InsertItemsOfTheDeals(a, tblItemsOrignal.getValueAt(j, 1).toString(),Integer.parseInt(tblItemsOrignal.getValueAt(j, 2).toString()));
                    
                }
                 DefaultTableModel model = (DefaultTableModel) tblItemsOrignal.getModel();
                 model.setRowCount(0);
                s.ShowDealsIntable(tblItems);
               
           }else{
               
           }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
                }
           
        }
    }//GEN-LAST:event_txtDoneActionPerformed

    private void btnItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDeleteActionPerformed
if(txtItemRate.getText().equals("")||txtItemItem.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fields Cannot be empty");}else{            
        
        int a = JOptionPane.showConfirmDialog(null,"Are you sure?");
            if(a==0){
                boolean b = s.deleteAllItemsIndeals(Integer.parseInt(txtItemsID.getText()));
                
                        if(b){
                            boolean c = s.deleteDeal(Integer.parseInt(txtItemsID.getText()));
                            if(c){
                                DefaultTableModel model = (DefaultTableModel) tblItemsOrignal.getModel();
                                model.setRowCount(0);
                                model = (DefaultTableModel) tblItems.getModel();
                                for (int j = 0; j < tblItems.getRowCount(); j++) {
                                    if(Integer.parseInt(model.getValueAt(j, 0).toString())==Integer.parseInt(txtItemsID.getText())){
                                        model.removeRow(j);
                                        break;
                                    }
                                }
                                txtItemItem.setText("");
                                txtItemRate.setText("");
                                txtItemsID.setText("");
                                combolistcatagory.setVisible(false);
                                jLabel6.setVisible(false);
                            }
                        }
            }}
        
    }//GEN-LAST:event_btnItemDeleteActionPerformed

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
            txtDone.setVisible(false);
        btnItemEdit2.setVisible(true);
        
            int r = tblItems.getSelectedRow();
            name = tblItems.getValueAt(r, 1).toString();
            if(r>=0){
            s.ShowDealsDeatilsIntable(tblItemsOrignal,Integer.parseInt(tblItems.getValueAt(r, 0).toString()));
            combolistcatagory.setVisible(true);
            txtItemsID.setText(tblItems.getValueAt(r, 0).toString());
            txtItemItem.setText(tblItems.getValueAt(r, 1).toString());
            txtItemRate.setText(tblItems.getValueAt(r, 2).toString());
            jLabel6.setVisible(true);}
    }//GEN-LAST:event_tblItemsMouseClicked

    private void btnItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemEditActionPerformed
                //s.UpdateDealnameorprice(Integer.parseInt(txtItemsID.getText()), txtItemItem.getText(), Double.parseDouble(txtItemRate.getText()));
        
        if(!(txtItemItem.getText().replaceAll("\\s+","").equalsIgnoreCase(name.replaceAll("\\s+","")))){
        if(s.checkfornameinDeals(txtItemItem.getText())!=-1){
            s.UpdateDealnameorprice(Integer.parseInt(txtItemsID.getText()), txtItemItem.getText(), Double.parseDouble(txtItemRate.getText()));
            s.ShowDealsIntable(tblItems);
            txtItemItem.setText("");
        txtItemRate.setText("");
        txtItemsID.setText("");
        }}else{
        
            s.UpdateDealnameorprice(Integer.parseInt(txtItemsID.getText()), txtItemItem.getText(), Double.parseDouble(txtItemRate.getText()));
            s.ShowDealsIntable(tblItems);
        txtItemItem.setText("");
        txtItemRate.setText("");
        txtItemsID.setText("");
        }
    }//GEN-LAST:event_btnItemEditActionPerformed

    private void tblItemsOrignalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsOrignalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblItemsOrignalMouseClicked

    private void btnItemAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemAdd1ActionPerformed
            
            btnItemEdit2.setVisible(false);
            txtDone.setVisible(true);
            jLabel6.setVisible(true);
            combolistcatagory.setVisible(true);
            txtItemItem.setText("");
            txtItemRate.setText("");
            txtItemsID.setText("");
             DefaultTableModel model = (DefaultTableModel) tblItemsOrignal.getModel();
             model.setRowCount(0);
    }//GEN-LAST:event_btnItemAdd1ActionPerformed

    private void btnItemEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemEdit1ActionPerformed
         DefaultTableModel model = (DefaultTableModel) tblItemsOrignal.getModel();
         int e = tblItemsOrignal.getSelectedRow();
             if(model.getValueAt(e, 0).equals("-1")){
                 model.removeRow(e);
             }else{
                 boolean b=s.deleteItemIndeals(Integer.parseInt(model.getValueAt(e, 0).toString()));
                 if(b){
                     System.out.println("Item Deleted");
                     model.removeRow(e);
                 }
             }
    }//GEN-LAST:event_btnItemEdit1ActionPerformed

    private void btnItemEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemEdit2ActionPerformed
        boolean a=false,c=false;
        DefaultTableModel model = (DefaultTableModel) tblItemsOrignal.getModel();
        for (int j = 0; j < model.getRowCount(); j++) {
        if(model.getValueAt(j, 0).equals("-1")){
                 
                  a = s.InsertItemsOfTheDeals(Integer.parseInt(txtItemsID.getText()),model.getValueAt(j, 1).toString(),Integer.parseInt(model.getValueAt(j, 2).toString()));
                 
                 
             }else{
                 
                 
                 c = s.updateDealsList(Integer.parseInt(model.getValueAt(j, 0).toString()), model.getValueAt(j, 1).toString(),Integer.parseInt(txtItemsID.getText()),Integer.parseInt(model.getValueAt(j, 2).toString()));
             }    
        }
        
        if(c || a){
            s.ShowDealsDeatilsIntable(tblItemsOrignal, Integer.parseInt(txtItemsID.getText()));
        }
        
           
        
    }//GEN-LAST:event_btnItemEdit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItemAdd1;
    private javax.swing.JButton btnItemDelete;
    private javax.swing.JButton btnItemEdit;
    private javax.swing.JButton btnItemEdit1;
    private javax.swing.JButton btnItemEdit2;
    private javax.swing.JButton btnItemReset;
    public javax.swing.JComboBox combolistcatagory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblItems;
    private javax.swing.JTable tblItemsOrignal;
    private javax.swing.JButton txtDone;
    private javax.swing.JTextField txtItemItem;
    private javax.swing.JTextField txtItemRate;
    private javax.swing.JTextField txtItemsID;
    // End of variables declaration//GEN-END:variables
}
