/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.frames;

import javax.swing.JOptionPane;
import pos.classes.DBmysqlconnection;

/**
 *
 * @author me
 */
public class Items extends javax.swing.JFrame {

    /**
     * Creates new form Items
     */
    DBmysqlconnection s;
    String name;
    int i;
    public Items(DBmysqlconnection s) {
        this.s =s;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        txtItemsID.setEditable(false);
        txtItemQuantity.setEditable(false);
        this.s.loadCatagorycomboBox(combolistcatagory);
        txttotalItems.setText(Integer.toString(this.s.LoadItems(tblItems)));
        jLabel2.setVisible(false);
        txtItemsID.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtItemsID = new javax.swing.JTextField();
        txtItemItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtItemQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnItemAdd = new javax.swing.JButton();
        btnItemReset = new javax.swing.JButton();
        btnItemEdit = new javax.swing.JButton();
        btnItemDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtItemRate = new javax.swing.JTextField();
        combolistcatagory = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnItemEdit1 = new javax.swing.JButton();
        txttotalItems = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Items");
        jLabel1.setOpaque(true);

        tblItems.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Items", "Rate", "Catagory"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItems.setRowHeight(20);
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItems);
        if (tblItems.getColumnModel().getColumnCount() > 0) {
            tblItems.getColumnModel().getColumn(0).setMinWidth(1);
            tblItems.getColumnModel().getColumn(0).setPreferredWidth(1);
            tblItems.getColumnModel().getColumn(0).setMaxWidth(1);
        }

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("ID");

        txtItemsID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtItemsID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        txtItemItem.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtItemItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("Items");

        txtItemQuantity.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtItemQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setText("Catagory");

        btnItemAdd.setBackground(new java.awt.Color(204, 255, 204));
        btnItemAdd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemAdd.setText("Add");
        btnItemAdd.setContentAreaFilled(false);
        btnItemAdd.setOpaque(true);
        btnItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemAddActionPerformed(evt);
            }
        });

        btnItemReset.setBackground(new java.awt.Color(204, 255, 204));
        btnItemReset.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemReset.setText("Reset");
        btnItemReset.setContentAreaFilled(false);
        btnItemReset.setOpaque(true);
        btnItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemResetActionPerformed(evt);
            }
        });

        btnItemEdit.setBackground(new java.awt.Color(204, 255, 204));
        btnItemEdit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemEdit.setText("Edit");
        btnItemEdit.setContentAreaFilled(false);
        btnItemEdit.setOpaque(true);
        btnItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemEditActionPerformed(evt);
            }
        });

        btnItemDelete.setBackground(new java.awt.Color(204, 255, 204));
        btnItemDelete.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemDelete.setText("Delete");
        btnItemDelete.setContentAreaFilled(false);
        btnItemDelete.setOpaque(true);
        btnItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDeleteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setText("Rate");

        txtItemRate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtItemRate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        combolistcatagory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combolistcatagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolistcatagoryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setText("Catagory");

        btnItemEdit1.setBackground(new java.awt.Color(204, 255, 204));
        btnItemEdit1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnItemEdit1.setText("Search");
        btnItemEdit1.setContentAreaFilled(false);
        btnItemEdit1.setOpaque(true);
        btnItemEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemEdit1ActionPerformed(evt);
            }
        });

        txttotalItems.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txttotalItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttotalItems.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel7.setText("Total Items");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtItemItem, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtItemsID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combolistcatagory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtItemRate, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnItemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnItemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnItemDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(txttotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnItemEdit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(txtItemsID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtItemItem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtItemRate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combolistcatagory))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnItemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnItemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnItemEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemResetActionPerformed
        s.LoadItems(tblItems);
        txtItemItem.setText("");
        txtItemQuantity.setText("");
        txtItemRate.setText("");
        txtItemsID.setText("");
    }//GEN-LAST:event_btnItemResetActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu m = new Menu(s);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosed

    private void combolistcatagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolistcatagoryActionPerformed
        txtItemQuantity.setText(combolistcatagory.getSelectedItem().toString());
    }//GEN-LAST:event_combolistcatagoryActionPerformed

    private void btnItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemAddActionPerformed
        if(txtItemQuantity.getText().equals("")||txtItemRate.getText().equals("")||txtItemItem.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fields Cannot be empty");
        }else if(s.checkfornameinitems(txtItemItem.getText())!= -1){
        try{           
            boolean b = s.InsertItems(txtItemItem.getText(), txtItemQuantity.getText(), Double.parseDouble(txtItemRate.getText()));
            if(b){
               txtItemItem.setText("");
               txtItemQuantity.setText("");
               txtItemRate.setText("");
               txtItemsID.setText("");
               txttotalItems.setText(Integer.toString(this.s.LoadItems(tblItems)));
           }else{
               
           }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
                }
           
        }
    }//GEN-LAST:event_btnItemAddActionPerformed

    private void btnItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDeleteActionPerformed
        
        
        if(s.DeleteItems(Integer.parseInt(txtItemsID.getText()))){
            JOptionPane.showMessageDialog(null, "ITEM DELETED");
            txttotalItems.setText(Integer.toString(this.s.LoadItems(tblItems)));
            txtItemItem.setText("");
            txtItemQuantity.setText("");
            txtItemRate.setText("");
            txtItemsID.setText("");
        }else{
            
        }
    }//GEN-LAST:event_btnItemDeleteActionPerformed

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
        i = tblItems.getSelectedRow();
        
        name = tblItems.getValueAt(i, 1).toString();
        txtItemsID.setText(tblItems.getValueAt(i, 0).toString());
        txtItemItem.setText(tblItems.getValueAt(i, 1).toString());
        txtItemRate.setText(tblItems.getValueAt(i, 2).toString());
        txtItemQuantity.setText(tblItems.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tblItemsMouseClicked

    private void btnItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemEditActionPerformed
        
        if(!(txtItemItem.getText().replaceAll("\\s+","").equalsIgnoreCase(name.replaceAll("\\s+","")))){
        if(s.checkfornameinitems(txtItemItem.getText())!=-1){
            s.update(Integer.parseInt(txtItemsID.getText()),txtItemItem.getText(), Double.parseDouble(txtItemRate.getText()), txtItemQuantity.getText());
            s.LoadItems(tblItems);
            txtItemItem.setText("");
        txtItemQuantity.setText("");
        txtItemRate.setText("");
        txtItemsID.setText("");
        }}else{
        
            s.update(Integer.parseInt(txtItemsID.getText()),txtItemItem.getText(), Double.parseDouble(txtItemRate.getText()), txtItemQuantity.getText());
            s.LoadItems(tblItems);
        txtItemItem.setText("");
        txtItemQuantity.setText("");
        txtItemRate.setText("");
        txtItemsID.setText("");
        }
    }//GEN-LAST:event_btnItemEditActionPerformed

    private void btnItemEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemEdit1ActionPerformed
        
        if(txtItemItem.getText().equals("")&& combolistcatagory.getSelectedItem().equals(" "))
        {
            JOptionPane.showMessageDialog(null, "Specify any searches!");
            
        }else if(!(txtItemItem.getText().equals(""))&&combolistcatagory.getSelectedItem().equals(" "))
        {
            s.searchByName(txtItemItem.getText(), tblItems);
            
        }else if(!(combolistcatagory.getSelectedItem().equals(" "))&& txtItemItem.getText().equals("") ){
            s.searchByCatagory(combolistcatagory.getSelectedItem().toString(), tblItems);
            
        }else{
            s.searchByCatagoryAndName(txtItemItem.getText(), combolistcatagory.getSelectedItem().toString(), tblItems);
        }
    }//GEN-LAST:event_btnItemEdit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItemAdd;
    private javax.swing.JButton btnItemDelete;
    private javax.swing.JButton btnItemEdit;
    private javax.swing.JButton btnItemEdit1;
    private javax.swing.JButton btnItemReset;
    public javax.swing.JComboBox combolistcatagory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtItemItem;
    private javax.swing.JTextField txtItemQuantity;
    private javax.swing.JTextField txtItemRate;
    private javax.swing.JTextField txtItemsID;
    private javax.swing.JTextField txttotalItems;
    // End of variables declaration//GEN-END:variables
}
