/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.frames;

import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowFilter.ComparisonType;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import pos.classes.DBmysqlconnection;

/**
 *
 * @author me
 */
public class SalesReport extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    DBmysqlconnection s;
    public SalesReport(DBmysqlconnection s) {
        this.s = s;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        comboItem.addItem("");
        s.loadItemscomboBox(comboItem);
        this.updateDate();
        this.updateYear();
        this.updateMonth();
        
        s.showOrderAll(tblSales);
        this.totalsales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboItem = new javax.swing.JComboBox<String>();
        checkCompleted = new javax.swing.JCheckBox();
        checkNotCompleted = new javax.swing.JCheckBox();
        checkTakeAway = new javax.swing.JCheckBox();
        checkHomeDelivery = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtTotalSales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboFromDay = new javax.swing.JComboBox<String>();
        comboFromYear = new javax.swing.JComboBox<String>();
        comboFromMonth = new javax.swing.JComboBox<String>();
        comboToYear = new javax.swing.JComboBox<String>();
        comboToMonth = new javax.swing.JComboBox<String>();
        comboToDay = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        btnPrint1 = new javax.swing.JButton();
        btnPrint2 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Sales Report");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("Items");

        comboItem.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        comboItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemActionPerformed(evt);
            }
        });

        checkCompleted.setBackground(new java.awt.Color(255, 255, 255));
        checkCompleted.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        checkCompleted.setText("Completed");
        checkCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCompletedActionPerformed(evt);
            }
        });

        checkNotCompleted.setBackground(new java.awt.Color(255, 255, 255));
        checkNotCompleted.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        checkNotCompleted.setText("Not Completed");
        checkNotCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNotCompletedActionPerformed(evt);
            }
        });

        checkTakeAway.setBackground(new java.awt.Color(255, 255, 255));
        checkTakeAway.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        checkTakeAway.setText("Take Away");
        checkTakeAway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTakeAwayActionPerformed(evt);
            }
        });

        checkHomeDelivery.setBackground(new java.awt.Color(255, 255, 255));
        checkHomeDelivery.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        checkHomeDelivery.setText("Dine In");
        checkHomeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHomeDeliveryActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 28)); // NOI18N
        jLabel4.setText("Total Sales");

        txtTotalSales.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotalSales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalSales.setText("0.00");
        txtTotalSales.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("From");

        comboFromDay.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboFromDay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));

        comboFromYear.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboFromYear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));

        comboFromMonth.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboFromMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        comboFromMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFromMonthActionPerformed(evt);
            }
        });

        comboToYear.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboToYear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        comboToYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboToYearActionPerformed(evt);
            }
        });

        comboToMonth.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboToMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));

        comboToDay.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboToDay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("to");

        btnPrint.setBackground(new java.awt.Color(153, 255, 153));
        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnPrint.setText("Reset");
        btnPrint.setContentAreaFilled(false);
        btnPrint.setOpaque(true);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tblSales.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        tblSales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order #", "Suborder #", "Date", "Item", "Qunatity", "Total", "Status", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSales.setIntercellSpacing(new java.awt.Dimension(10, 1));
        tblSales.setRowHeight(20);
        jScrollPane1.setViewportView(tblSales);

        btnPrint1.setBackground(new java.awt.Color(153, 255, 153));
        btnPrint1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnPrint1.setText("Print");
        btnPrint1.setContentAreaFilled(false);
        btnPrint1.setOpaque(true);
        btnPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrint1ActionPerformed(evt);
            }
        });

        btnPrint2.setBackground(new java.awt.Color(153, 255, 153));
        btnPrint2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnPrint2.setText("Search");
        btnPrint2.setContentAreaFilled(false);
        btnPrint2.setOpaque(true);
        btnPrint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrint2ActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 28)); // NOI18N
        jLabel7.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboItem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel4)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPrint1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(checkCompleted)
                                .addGap(18, 18, 18)
                                .addComponent(checkNotCompleted)
                                .addGap(18, 18, 18)
                                .addComponent(checkTakeAway)
                                .addGap(18, 18, 18)
                                .addComponent(checkHomeDelivery)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(comboFromDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFromMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(comboFromYear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(comboToDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(comboToMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(comboToYear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnPrint2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(comboItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel7))
                                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkCompleted)
                                    .addComponent(checkNotCompleted)
                                    .addComponent(checkTakeAway)
                                    .addComponent(checkHomeDelivery)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPrint1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFromDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboFromYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboFromMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboToDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboToMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboToYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4))
                            .addComponent(txtTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void updateDate(){
        for (int i = 1; i <= 31; i++) {
            if(i<10){
            comboFromDay.addItem("0"+Integer.toString(i));
            comboToDay.addItem("0"+Integer.toString(i));}
            else{
                comboFromDay.addItem(Integer.toString(i));
            comboToDay.addItem(Integer.toString(i));
            }
        }
    }
    
    public void updateYear(){
        int j = 2015;
        for (int i = 0; i < 20; i++) {
            comboFromYear.addItem(Integer.toString(j+i));
            comboToYear.addItem(Integer.toString(j+i));
        }
    }
    
    public void updateMonth(){
        int j = 1;
        for (int i = 0; i < 12; i++) {
            
            if(i<9){
            comboFromMonth.addItem("0"+Integer.toString(j+i));
            comboToMonth.addItem("0"+Integer.toString(j+i));}else{
            comboFromMonth.addItem(Integer.toString(j+i));
            comboToMonth.addItem(Integer.toString(j+i));    
            }
        }
    }
    public void totalsales(){
        double sum=0;
        for (int q = 0; q < tblSales.getRowCount(); q++) {
            
            if(tblSales.getValueAt(q, 6).toString().equals("Completed")){
            sum = sum + Double.parseDouble(tblSales.getValueAt(q, 5).toString());}
        }
        txtTotalSales.setText(Double.toString(sum));
    }
    
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        checkNotCompleted.setSelected(false);
        txtSearch.setText("");
         checkHomeDelivery.setSelected(false);
         checkCompleted.setSelected(false);
         checkTakeAway.setSelected(false);
         DefaultTableModel f = new DefaultTableModel();
         tblSales.setRowSorter(null);
         f =(DefaultTableModel) tblSales.getModel();
         f.setRowCount(0);
         s.showOrderAll(tblSales);
         this.totalsales();
         
         
    }//GEN-LAST:event_btnPrintActionPerformed

    private void comboToYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboToYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboToYearActionPerformed

    private void comboFromMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFromMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFromMonthActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu m = new Menu(s);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosed

    private void btnPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrint1ActionPerformed
        try {
//            tblSales.print(JTable.PrintMode.FIT_WIDTH, null, null, true,null,true);
            PrinterJob job = PrinterJob.getPrinterJob();
PageFormat pf = job.defaultPage();
Paper paper = pf.getPaper();
double margin = 20.;
paper.setImageableArea(margin, 
        paper.getImageableY(), 
        paper.getWidth() - 2* margin, paper.getImageableHeight());
pf.setPaper(paper);
job.setPrintable(tblSales.getPrintable(JTable.PrintMode.FIT_WIDTH, null, null), 
        job.validatePage(pf));
job.print();
        } catch (PrinterException ex) {
            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HeadlessException ex) {
            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrint1ActionPerformed

    private void btnPrint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrint2ActionPerformed
            String sdate = comboFromDay.getSelectedItem().toString()+"/"+comboFromMonth.getSelectedItem().toString()+"/"+comboFromYear.getSelectedItem().toString();
            String edate = comboToDay.getSelectedItem().toString()+"/"+comboToMonth.getSelectedItem().toString()+"/"+comboToYear.getSelectedItem().toString();
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Date date1 = null;
                try {
                    date1 = sdf.parse(sdate);
                } catch (ParseException ex) {
                    Logger.getLogger(DBmysqlconnection.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                Date date2 = null;
                try {
                    date2 = sdf.parse(edate);
                } catch (ParseException ex) {
                    Logger.getLogger(DBmysqlconnection.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                if(date1.after(date2)){
                    
                }
                
                
                s.showOrderAllBydatesS(tblSales, date1, date2);
                
                this.totalsales();

    }//GEN-LAST:event_btnPrint2ActionPerformed

    private void comboItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemActionPerformed

        DefaultTableModel model1 = (DefaultTableModel) tblSales.getModel();
        if(!(comboItem.getSelectedItem().equals(""))){
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model1);
        RowFilter<DefaultTableModel, Object> rf  = RowFilter.regexFilter(comboItem.getSelectedItem().toString(),3);
                sorter.setRowFilter(rf);
                     tblSales.setRowSorter(sorter);
        this.totalsales();
        }
    }//GEN-LAST:event_comboItemActionPerformed

    private void checkTakeAwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTakeAwayActionPerformed
        if(checkTakeAway.isSelected()){
        DefaultTableModel model1 = (DefaultTableModel) tblSales.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model1);
        RowFilter<DefaultTableModel, Object> rf  = RowFilter.regexFilter("TAKE AWAY",7);
                sorter.setRowFilter(rf);
                     tblSales.setRowSorter(sorter);
        this.totalsales();}
        checkNotCompleted.setSelected(false);
         checkHomeDelivery.setSelected(false);
         checkCompleted.setSelected(false);
         this.totalsales();
        
    }//GEN-LAST:event_checkTakeAwayActionPerformed

    private void checkNotCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNotCompletedActionPerformed
         if(checkNotCompleted.isSelected()){
        DefaultTableModel model1 = (DefaultTableModel) tblSales.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model1);
        RowFilter<DefaultTableModel, Object> rf  = RowFilter.regexFilter("Canceled",6);
                sorter.setRowFilter(rf);
                     tblSales.setRowSorter(sorter);
        this.totalsales();}
         checkTakeAway.setSelected(false);
         
         checkHomeDelivery.setSelected(false);
         checkCompleted.setSelected(false);
         this.totalsales();
        
    }//GEN-LAST:event_checkNotCompletedActionPerformed

    private void checkHomeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHomeDeliveryActionPerformed
        if(checkHomeDelivery.isSelected()){
        DefaultTableModel model1 = (DefaultTableModel) tblSales.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model1);
        RowFilter<DefaultTableModel, Object> rf  = RowFilter.regexFilter("Dine In",7);
                sorter.setRowFilter(rf);
                     tblSales.setRowSorter(sorter);
        this.totalsales();}
        checkNotCompleted.setSelected(false);
         checkTakeAway.setSelected(false);
         checkCompleted.setSelected(false);
        this.totalsales();
    }//GEN-LAST:event_checkHomeDeliveryActionPerformed

    private void checkCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCompletedActionPerformed
        if(checkCompleted.isSelected()){
        DefaultTableModel model1 = (DefaultTableModel) tblSales.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model1);
        RowFilter<DefaultTableModel, Object> rf  = RowFilter.regexFilter("Completed",6);
                sorter.setRowFilter(rf);
                     tblSales.setRowSorter(sorter);
        this.totalsales();}
        checkNotCompleted.setSelected(false);
         checkHomeDelivery.setSelected(false);
         checkTakeAway.setSelected(false);
         this.totalsales();
    }//GEN-LAST:event_checkCompletedActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
DefaultTableModel model1 = (DefaultTableModel) tblSales.getModel();
        if(!(txtSearch.getText().equals(" "))){
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model1);
        RowFilter<DefaultTableModel, Object> rf  = RowFilter.regexFilter(txtSearch.getText(),0);
                sorter.setRowFilter(rf);
                     tblSales.setRowSorter(sorter);
        this.totalsales();
        }        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        DefaultTableModel model1 = (DefaultTableModel) tblSales.getModel();
        if(!(txtSearch.getText().equals(" "))){
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model1);
        RowFilter<DefaultTableModel, Object> rf  = RowFilter.regexFilter(txtSearch.getText(),0);
                sorter.setRowFilter(rf);
                     tblSales.setRowSorter(sorter);
        this.totalsales();
        }            }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnPrint1;
    private javax.swing.JButton btnPrint2;
    private javax.swing.JCheckBox checkCompleted;
    private javax.swing.JCheckBox checkHomeDelivery;
    private javax.swing.JCheckBox checkNotCompleted;
    private javax.swing.JCheckBox checkTakeAway;
    private javax.swing.JComboBox<String> comboFromDay;
    private javax.swing.JComboBox<String> comboFromMonth;
    private javax.swing.JComboBox<String> comboFromYear;
    private javax.swing.JComboBox<String> comboItem;
    private javax.swing.JComboBox<String> comboToDay;
    private javax.swing.JComboBox<String> comboToMonth;
    private javax.swing.JComboBox<String> comboToYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tblSales;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotalSales;
    // End of variables declaration//GEN-END:variables
}
