/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.frames;

import javax.swing.JOptionPane;
import pos.classes.DBmysqlconnection;

/**
 *
 * @author me
 */
public class StockManagement extends javax.swing.JFrame {

    String name;
    DBmysqlconnection s;
    public StockManagement(DBmysqlconnection s) {
        this.s =s;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        txttotalstock.setText(Integer.toString(s.LoadStock(tblStock)));
        this.txtStockID.setVisible(false);
        this.jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtStockID = new javax.swing.JTextField();
        txtStockStock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStockQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnStockAdd = new javax.swing.JButton();
        btnStockReset = new javax.swing.JButton();
        btnStockEdit = new javax.swing.JButton();
        btnStockDelete = new javax.swing.JButton();
        txttotalstock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Stock Management");
        jLabel1.setOpaque(true);

        tblStock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Stock", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStock.setRowHeight(20);
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);
        if (tblStock.getColumnModel().getColumnCount() > 0) {
            tblStock.getColumnModel().getColumn(0).setMinWidth(1);
            tblStock.getColumnModel().getColumn(0).setPreferredWidth(1);
            tblStock.getColumnModel().getColumn(0).setMaxWidth(1);
            tblStock.getColumnModel().getColumn(1).setMinWidth(200);
        }

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("ID");

        txtStockID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtStockID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        txtStockStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtStockStock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("Stock");

        txtStockQuantity.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtStockQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setText("Quantity");

        btnStockAdd.setBackground(new java.awt.Color(204, 255, 204));
        btnStockAdd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnStockAdd.setText("Add");
        btnStockAdd.setContentAreaFilled(false);
        btnStockAdd.setOpaque(true);
        btnStockAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockAddActionPerformed(evt);
            }
        });

        btnStockReset.setBackground(new java.awt.Color(204, 255, 204));
        btnStockReset.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnStockReset.setText("Reset");
        btnStockReset.setContentAreaFilled(false);
        btnStockReset.setOpaque(true);
        btnStockReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockResetActionPerformed(evt);
            }
        });

        btnStockEdit.setBackground(new java.awt.Color(204, 255, 204));
        btnStockEdit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnStockEdit.setText("Edit");
        btnStockEdit.setContentAreaFilled(false);
        btnStockEdit.setOpaque(true);
        btnStockEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockEditActionPerformed(evt);
            }
        });

        btnStockDelete.setBackground(new java.awt.Color(204, 255, 204));
        btnStockDelete.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnStockDelete.setText("Delete");
        btnStockDelete.setContentAreaFilled(false);
        btnStockDelete.setOpaque(true);
        btnStockDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockDeleteActionPerformed(evt);
            }
        });

        txttotalstock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txttotalstock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttotalstock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel7.setText("Total Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtStockStock, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStockID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnStockEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStockAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnStockDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnStockReset, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttotalstock, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtStockID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtStockStock, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtStockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStockAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStockReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStockEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStockDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotalstock, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStockResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockResetActionPerformed
        s.LoadStock(tblStock);
        txtStockID.setText("");
        txtStockStock.setText("");
        txtStockQuantity.setText("");
    }//GEN-LAST:event_btnStockResetActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu m = new Menu(s);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosed

    private void btnStockAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockAddActionPerformed
        if(txtStockStock.getText().equals("")||txtStockQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fields Cannot be empty");
        }else if(s.checkfornameinStock(txtStockStock.getText())!= -1){
           boolean b = s.InsertStock(txtStockStock.getText(),txtStockQuantity.getText());
           
           if(b){
               txttotalstock.setText(Integer.toString(s.LoadStock(tblStock)));
                txtStockID.setText("");
        txtStockStock.setText("");
        txtStockQuantity.setText("");
           }else{
               
           }
        }
    }//GEN-LAST:event_btnStockAddActionPerformed

    private void btnStockEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockEditActionPerformed

        if(!(txtStockStock.getText().replaceAll("\\s+","").equalsIgnoreCase(name.replaceAll("\\s+","")))){
        if(s.checkfornameinStock(txtStockStock.getText())!=-1){
            s.updateStock(Integer.parseInt(txtStockID.getText()),txtStockStock.getText(), txtStockQuantity.getText());
            s.LoadStock(tblStock);
             txtStockID.setText("");
        txtStockStock.setText("");
        txtStockQuantity.setText("");
        }}else{
            s.updateStock(Integer.parseInt(txtStockID.getText()),txtStockStock.getText(), txtStockQuantity.getText());
            s.LoadStock(tblStock);
             txtStockID.setText("");
        txtStockStock.setText("");
        txtStockQuantity.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnStockEditActionPerformed

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        int i = tblStock.getSelectedRow();
        
        name = tblStock.getValueAt(i, 1).toString();
        txtStockID.setText(tblStock.getValueAt(i, 0).toString());
        txtStockStock.setText(tblStock.getValueAt(i, 1).toString());
        txtStockQuantity.setText(tblStock.getValueAt(i, 2).toString());
        
    }//GEN-LAST:event_tblStockMouseClicked

    private void btnStockDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockDeleteActionPerformed
        if(s.DeleteStock(Integer.parseInt(txtStockID.getText()))){
            JOptionPane.showMessageDialog(null, "ITEM DELETED");
            txttotalstock.setText(Integer.toString(s.LoadStock(tblStock)));
            txtStockID.setText("");
            txtStockStock.setText("");
            txtStockQuantity.setText("");
        }else{
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnStockDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStockAdd;
    private javax.swing.JButton btnStockDelete;
    private javax.swing.JButton btnStockEdit;
    private javax.swing.JButton btnStockReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtStockID;
    private javax.swing.JTextField txtStockQuantity;
    private javax.swing.JTextField txtStockStock;
    private javax.swing.JTextField txttotalstock;
    // End of variables declaration//GEN-END:variables
}
